version: '2'
services:
  how_java_today_app-app:
    image: how_java_today_app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://how_java_today_app-postgresql:5432/how_java_today_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  how_java_today_app-postgresql:
    extends:
      file: postgresql.yml
      service: how_java_today_app-postgresql
