version: '2'
services:
  how_java_today_app-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/how_java_today_app/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=how_java_today_app
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
